### ISSUE TITLE
Hapi v17 Compatibility Release

### ISSUE THREAD

**Issue by timcosta** [p-meier/hapi-api-version#18]
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`. This is a breaking change that will make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [x] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [x] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [x] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.

**Comment by timcosta** [comment]
Will be updating

**Comment by geekgugi** [comment]
Any plan to update the plugin?

**Comment by gugwad** [comment]
@timcosta Submitted a PR for transition to Hapi 17. Please review and comment.

**Comment by timcosta** [comment]
@gugwad thanks for contributing the PR - I've been slammed at work recently and just haven't had the time. Left a few minor comments.

**Comment by gugwad** [comment]
@timcosta Fixed review comments for PR.

**Comment by timcosta** [comment]
@gugwad your changes are now in master, thank you! Working on coordinating a release on npm with @p-meier.

**Comment by timcosta** [comment]
@gugwad 
```➜  npm publish
+ hapi-api-version@2.0.0```
v2.0.0 has been released.
